--- #YAML:1.0
name:               WWW-DirectAdmin-API
version:            0.02
abstract:           Access the DirectAdmin API with Perl
author:
    - Lee Carmichael <lcarmich@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:      0
    HTML::Entities:    0
    HTTP::Request:     0
    LWP::UserAgent:    0
    Params::Validate:  0
    Test::More:        0
    URI:               0
resources:
    bugtracker:  https://github.com/lecar-red/WWW-DirectAdmin-API/issues
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/lecar-red/WWW-DirectAdmin-API
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
